apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
  namespace: blog-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
      - name: blog-app
        image: your-dockerhub-username/blog-app:latest
        ports:
        - containerPort: 5001
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://i222615:2251193@web-lab11.okyyj.mongodb.net/BlogApp"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi" 