apiVersion: v1
kind: Service
metadata:
  name: blog-app-service
  namespace: blog-namespace
spec:
  type: NodePort
  selector:
    app: blog-app
  ports:
    - port: 80
      targetPort: 5001
      nodePort: 30007 